### ISSUE TITLE
실행문제

### ISSUE THREAD

**Issue by chan5267** [dhfhfk/scheme#2]
(node:15504) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by dhfhfk** [comment]
자가진단 서버에서 유명 호스팅 대역을 막아 http 통신으로 바꾼 것이 저 메시지를 출력합니다.
아마 정상적인 사용에는 아무 영향 없을 것입니다.

**Comment by chan5267** [comment]
여쭈어 보고싶은게 많은데 연락망 없을까요?

**Comment by chan5267** [comment]
index.js를 실행할때, 계속 저 문구가 뜨고 실행이 불가합니다
