### ISSUE TITLE
ERROR #2

### ISSUE THREAD

**Issue by chan5267** [dhfhfk/scheme#4]
uncaught DiscordAPIError DiscordAPIError: Missing Access
    at DiscordAPIError ([c:\Users\a\Downloads\scheme-main]() (1)\scheme-main\node_modules\discord.js\src\rest\DiscordAPIError.js:9:5)
    at execute ([c:\Users\a\Downloads\scheme-main]() (1)\scheme-main\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
계속 질문 드려 죄송합니다..ㅠ

**Comment by dhfhfk** [comment]
봇을 초대하실 때
![whale_20220326_214023](https://user-images.githubusercontent.com/68490827/160239901-02da2a4b-2367-4edd-abc8-ff504f2cb0a9.png)
 applications.commands 옵션을 활성화 시킨 URL 로 초대하셔야 권한이 부여됩니다!

**Comment by chan5267** [comment]
감사합니다!

**Comment by chan5267** [comment]
> 봇을 초대하실 때 ![whale_20220326_214023](https://user-images.githubusercontent.com/68490827/160239901-02da2a4b-2367-4edd-abc8-ff504f2cb0a9.png) applications.commands 옵션을 활성화 시킨 URL 로 초대하셔야 권한이 부여됩니다! 혹은 초대 링크 뒤에 &scope=bot%20applications.commands 를 붙여서 사용하시면 됩니다

원래 명령어가 관리자명령어만 있나요?

**Comment by chan5267** [comment]
![f15261d0356ca7993af5926737731714](https://user-images.githubusercontent.com/100329087/160240163-42cba675-c45a-4071-b3bd-32662c94a283.png)

**Comment by dhfhfk** [comment]
모든 서버에 적용되는 global 일반 명령어들은 20분 ~ 1시간 정도 적용 시간이 필요해서 아직 안보이는 것 같네요

**Comment by dhfhfk** [comment]
친구추가 드렸습니다!
